In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("salaries.csv")

In [3]:
df.head()

work_year experience_level employment_type                job_title  \
0       2025               MI              FT                  Analyst   
1       2025               MI              FT                  Analyst   
2       2025               SE              FT        Data Quality Lead   
3       2025               SE              FT        Data Quality Lead   
4       2025               MI              FT  Data Quality Specialist   

   salary salary_currency  salary_in_usd employee_residence  remote_ratio  \
0  142000             USD         142000                 US             0   
1   87000             USD          87000                 US             0   
2  218700             USD         218700                 US             0   
3  163200             USD         163200                 US             0   
4  121524             USD         121524                 US             0   

  company_location company_size  
0               US            M  
1               US            M  
2               US            M  
3               US            M  
4               US            M

In [4]:
df.tail()

work_year experience_level employment_type                 job_title  \
146343       2020               SE              FT            Data Scientist   
146344       2021               MI              FT  Principal Data Scientist   
146345       2020               EN              FT            Data Scientist   
146346       2020               EN              CT     Business Data Analyst   
146347       2021               SE              FT            Data Scientist   

         salary salary_currency  salary_in_usd employee_residence  \
146343   412000             USD         412000                 US   
146344   151000             USD         151000                 US   
146345   105000             USD         105000                 US   
146346   100000             USD         100000                 US   
146347  7000000             INR          94665                 IN   

        remote_ratio company_location company_size  
146343           100               US            L  
146344           100               US            L  
146345           100               US            S  
146346           100               US            L  
146347            50               IN            L

In [5]:
df.describe()

work_year        salary  salary_in_usd   remote_ratio
count  146348.000000  1.463480e+05  146348.000000  146348.000000
mean     2024.415646  1.629267e+05  157485.290691      20.901550
std         0.674981  2.106091e+05   74134.134223      40.591728
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060000e+05  106000.000000       0.000000
50%      2025.000000  1.470000e+05  146100.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146348 entries, 0 to 146347
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype 
---  ------              --------------   ----- 
 0   work_year           146348 non-null  int64 
 1   experience_level    146348 non-null  object
 2   employment_type     146348 non-null  object
 3   job_title           146348 non-null  object
 4   salary              146348 non-null  int64 
 5   salary_currency     146348 non-null  object
 6   salary_in_usd       146348 non-null  int64 
 7   employee_residence  146348 non-null  object
 8   remote_ratio        146348 non-null  int64 
 9   company_location    146348 non-null  object
 10  company_size        146348 non-null  object
dtypes: int64(4), object(7)
memory usage: 12.3+ MB


In [7]:
df['remote_ratio'].unique()

array([  0, 100,  50], dtype=int64)

In [8]:
df['work_year'].unique()

array([2025, 2024, 2023, 2022, 2020, 2021], dtype=int64)

In [9]:
df['experience_level'].unique()

array(['MI', 'SE', 'EX', 'EN'], dtype=object)

In [10]:
df['employment_type'].unique()

array(['FT', 'CT', 'PT', 'FL'], dtype=object)

In [11]:
df['job_title'].unique()

array(['Analyst', 'Data Quality Lead', 'Data Quality Specialist',
       'Data Modeler', 'Software Engineer', 'Machine Learning Engineer',
       'Manager', 'Developer', 'Engineer', 'Head of Data', 'Director',
       'Data Scientist', 'Data Developer', 'Research Scientist',
       'Product Owner', 'Data Analyst', 'Data Engineer', 'AI Engineer',
       'Architect', 'Data Architect', 'Economist',
       'Software Development Engineer', 'Product Manager',
       'Solutions Architect', 'Backend Engineer', 'DevOps Engineer',
       'Systems Engineer', 'Consultant', 'Research Assistant',
       'Solutions Engineer', 'Researcher', 'Analytics Manager',
       'Engineering Manager', 'Solution Engineer', 'Research Specialist',
       'Lead Engineer', 'Applied Scientist', 'Data Operations',
       'Solution Architect', 'Business Intelligence Engineer',
       'SAS Developer', 'Data Governance Manager',
       'Business Intelligence Lead', 'Software Developer',
       'System Engineer', 'Staff Eng

In [12]:
df['salary'].unique()

array([142000,  87000, 218700, ..., 138350, 423000, 412000], dtype=int64)

In [13]:
df['salary_currency'].unique()

array(['USD', 'GBP', 'CHF', 'EUR', 'SGD', 'CAD', 'CZK', 'INR', 'PLN',
       'NOK', 'MXN', 'PHP', 'JPY', 'HUF', 'AUD', 'TWD', 'BRL', 'ZAR',
       'DKK', 'ILS', 'TRY', 'SEK', 'NZD', 'HKD', 'THB', 'CLP'],
      dtype=object)

In [14]:
df['salary_in_usd'].unique()

array([142000,  87000, 218700, ...,  28369, 412000,  94665], dtype=int64)

In [15]:
df['employee_residence'].unique()

array(['US', 'CA', 'BE', 'GB', 'CH', 'GR', 'SG', 'SK', 'FR', 'NL', 'CZ',
       'NZ', 'AU', 'ES', 'IN', 'PL', 'DE', 'IT', 'AT', 'HR', 'FI', 'PR',
       'AR', 'PT', 'BR', 'LT', 'IE', 'PH', 'RO', 'ML', 'NO', 'CL', 'MY',
       'SV', 'CO', 'DO', 'MX', 'GT', 'CR', 'LV', 'ZA', 'EE', 'EG', 'JO',
       'CY', 'UA', 'TH', 'JM', 'JP', 'MT', 'MK', 'SI', 'HK', 'LS', 'ID',
       'PE', 'HU', 'PA', 'LU', 'DZ', 'KE', 'CD', 'SE', 'KR', 'TW', 'TR',
       'NG', 'DK', 'AE', 'BG', 'RS', 'EC', 'XK', 'ZM', 'AM', 'RW', 'IL',
       'LB', 'PK', 'HN', 'VE', 'BM', 'VN', 'GE', 'SA', 'OM', 'BA', 'UG',
       'MU', 'QA', 'RU', 'TN', 'GH', 'AD', 'MD', 'UZ', 'CF', 'KW', 'IR',
       'AS', 'CN', 'BO', 'IQ', 'JE'], dtype=object)

In [16]:
df['company_location'].unique()

array(['US', 'CA', 'BE', 'GB', 'CH', 'GR', 'SG', 'SK', 'FR', 'NL', 'CZ',
       'NZ', 'AU', 'ES', 'IN', 'PL', 'DE', 'IT', 'AT', 'HR', 'FI', 'PR',
       'AR', 'PT', 'BR', 'LT', 'IE', 'PH', 'RO', 'ML', 'NO', 'CL', 'MY',
       'SV', 'CO', 'DO', 'MX', 'GT', 'CR', 'LV', 'ZA', 'EE', 'EG', 'JO',
       'CY', 'UA', 'TH', 'JM', 'JP', 'MT', 'MK', 'SI', 'HK', 'LS', 'PE',
       'HU', 'PA', 'LU', 'DZ', 'KE', 'CD', 'SE', 'KR', 'TW', 'TR', 'DK',
       'AE', 'BG', 'ID', 'RS', 'EC', 'XK', 'ZM', 'AM', 'IL', 'LB', 'NG',
       'PK', 'HN', 'VE', 'AS', 'SA', 'OM', 'BA', 'VN', 'GI', 'MU', 'RU',
       'QA', 'GH', 'AD', 'CF', 'IR', 'BS', 'IQ', 'CN', 'MD'], dtype=object)

In [17]:
df['company_size'].unique()

array(['M', 'L', 'S'], dtype=object)

In [18]:
df['remote_ratio'].unique()

array([  0, 100,  50], dtype=int64)

In [19]:
#df.to_csv('salaries.csv', index=False)

## Splitting the Data for Predictive Analysis

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X = df.drop(columns=['salary_in_usd'])

In [44]:
y = df['salary_in_usd']

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)